# Generated by Django 5.1.6 on 2025-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="phone",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="เบอร์โทรศัพท์มือถือ"
            ),
        ),
    ]
