# Generated by Django 5.1.6 on 2025-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_dentist_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
